### ISSUE TITLE
DNS support?

### ISSUE THREAD

**Issue by overheat** [embassy-rs/embassy#1120]
I found that drogue-device already implement a DNS in [device/src/net/dns.rs](https://github.com/drogue-iot/drogue-device/blob/d08f1dd6dac5fd61231dd94d2de6461163b9380f/device/src/net/dns.rs). It's not actually send DNS request (query), but a static IP.

I am not sure. Do we need to implement wrapping of smoltcp's DNS in embassy-net? Then application could leverage it.

**Comment by lulf** [comment]
I think the way forward here would be to create a generic async DNS client that implements the DNS traits and uses the UDP traits from embedded-nal-async to do the UDP communication. Embassy-net and others can then implement the traits from e-n-a and it would work other networking implementations as well (like AT-command drivers).

I think this can live in a separate repo as it's not really dependent on embassy and should be possible to implement just using the async traits from e-n-a.

**Comment by Dirbaio** [comment]
smoltcp already has a `DnsSocket`. `embassy-net` should get a wrapper for that. 

It's a socket instead of a stack-independent impl on top of UDP because that allows constructing the DNS request and parsing the DNS response in-place inside the network device's buffers. Otherwise if you use `UdpSocket` you need extra buffers to hold the tx/rx queues. There's some discussion on that here https://github.com/smoltcp-rs/smoltcp/pull/465

This does mean you can't use it with an AT-command-based UDP stack. However, these often already have a DNS client (or even allow directly specifying DNS names in commands like TCP connect), so I think it's rather uncommon to need a custom DNS on top of that...

**Comment by overheat** [comment]
> 

I tried DNS example in smoltcp, but looks it not work.
https://github.com/smoltcp-rs/smoltcp/issues/731
