### ISSUE TITLE
embassy-nrf: New Event/Task types

### ISSUE THREAD

**Issue by fnafnio** [embassy-rs/embassy#121]
So I've just tried the new updates and found no way to link up timer compare events to PPI, as `ppi::Event` is not implemented for the timer events and `Event::from_reg` is private. 
Will `Event::from_reg` eventually become public or be implemented for the rest of the peripherals?
For now I will just make `from_reg` public and use it like in BufferedUarte, but I might be missing something

**Comment by Dirbaio** [comment]
The inner pointer in Task and Event is public, so you can implement a `from_reg` equivalent in your crate.

```rust
pub struct Task(pub NonNull<()>);
pub struct Event(pub NonNull<()>);
```

This is intentional, because I want to remove all references to the PAC from the public API, so it can be bumped or replaced without breaking the public API. 

I'm aware short-term it's less usable. This would also be improved by implementing a Timer HAL in embassy.

(tldr of the reasons for that: We may switch to something else due to a few problems with the PAC design: slow compile, can only link one major version in the binary, almost all PAC changes are breaking so require a major version, the owned singletons can't be semver-tricked due to Deref impl, https://github.com/rust-embedded/wg/pull/387, and for stm32 https://github.com/stm32-rs/meta/issues/4)
