### ISSUE TITLE
Improve efficiency of `embassy::net::Stack.poll()`

### ISSUE THREAD

**Issue by MabezDev** [embassy-rs/embassy#1212]
`poll` calls smoltcp's `poll_at` method in a hot loop (but yields to the executor each iteration). This seems very inefficient because we could just wait until the `poll_at` instant. It also makes the waker registration for the link_state somewhat redundant too, because it gets polled constantly too.

What's the purpose of using a `poll_fn` loop? Could we make this properly async?

**Comment by Dirbaio** [comment]
It shouldn't be a hot loop. Have you actually checked if it is, or is it just from reading the code?

It's creating a timer from poll_at and polling it once: https://github.com/embassy-rs/embassy/blob/master/embassy-net/src/lib.rs#L417

ONly if the timer is already expired, it immediately wakes itself. Otherwise, the timer poll will have registered the waker to be woken at `poll_at` expiration.

**Comment by MabezDev** [comment]
In my experience yes, it appears to be a hot loop. I only noticed because I put a print inside the `link_state` driver function and it spewed out thousands of prints :sweat_smile:.

**Comment by Dirbaio** [comment]
I just double-checked running the nrf `usb_ethernet` example, and it doesn't poll in a hot loop. It might be an issue in the driver.

**Comment by MabezDev** [comment]
Yep, you were right! I debugged a bit further and my transmit waker was outside the check for whether we have to actually send something or not... Oops :sweat_smile:. Apologies for the noise.

**Comment by Dirbaio** [comment]
btw you have to wake the waker only when an earlier  `transmt/receive` call returned None because there was no buffer space, and then buffer space becomes available. No need to wake on all "tx done".

**Comment by MabezDev** [comment]
Thanks! I'll look into doing that too :).
