### ISSUE TITLE
embassy-net: TCP sockets discards unsent data on Drop 

### ISSUE THREAD

**Issue by kbleeke** [embassy-rs/embassy#1223]
I have a relatively simple program that
1. accepts a new connection
2. writes some bme280 measurements to the socket
3. drops the socket and waits for a new connection

This results in no data being transmitted. As far as I can tell, the problem is that Drop immediately unregisters the socket's buffers from the network stack so that the stack never gets to execute the write.

I would have expected all outdoing data to be sent. Alternatively, there should be a method that waits for this.

```rust
let mut rx_buffer = [0; 4096];
let mut tx_buffer = [0; 4096];
let mut buf = [0; 4096];

loop {
    let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);
    if let Err(e) = socket.accept(1234).await {
        defmt::warn!("accept error: {:?}", e);
        continue;
    }
    let m = bme.measure(&mut Delay).await.unwrap();
    let n = serde_json_core::to_slice(&m, &mut buf).unwrap();

    match socket.write_all(&buf[..n]).await {
        Ok(()) => {}
        Err(e) => {
            defmt::warn!("write error: {:?}", e);
            break;
        }
    }
}
```

**Comment by Dirbaio** [comment]
This is intended behavior. It *has* to be this way because the data is in the buffers you provide. If you drop the socket and deallocate the buffers, the stack has nowhere to store it.

One solution would be to make `.flush()` wait until all the data is ack'd at the TCP level. It's not currently implemented, but PR's welcome.

However, in practice, if you want this to be reliable, you probably want some "application-level ACK" that the data was received correctly on the other end. Waiting for TCP ACKs is not enough, because:
- ACK only means it has reached the remote OS's TCP stack, it doesn't mean the data has been delivered to the application and the application has successfully stored it on a database or whatever.
- If you go through WAN, there can be TCP middleboxes / proxies that will ACK the data and then take charge of sending it to the peer.

**Comment by kbleeke** [comment]
That makes sense. Thanks for the tip for application-level ACKs. I don't think, I require them specifically in my case but waiting for incoming data would certainly fix my issue.

I think I came up with an implementation for flush, I've opened a PR
