### ISSUE TITLE
embassy_net::Stack::run thrashes

### ISSUE THREAD

**Issue by wyager** [embassy-rs/embassy#1646]
Calling `stack.run()` thrashes the CPU (including preventing lower-priority tasks from running on rtic).

I added some logging here to test it on my chip - you can look at the diff from main to see what logging I added.

https://github.com/wyager/embassy/tree/wyager-ethernet-thrashing

This function gets run thousands of times a second, starving other stuff on the system: https://github.com/embassy-rs/embassy/blob/main/embassy-net/src/lib.rs#L666

@Dirbaio thought it might be this TODO https://github.com/embassy-rs/embassy/blob/82d765689aa0f922d0b43e402eaa3d911b2d461d/embassy-stm32/src/eth/mod.rs#L84

**Comment by Dirbaio** [comment]
[relevant discussion](https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$u1VXiP5KoNszPb4MHlk6-PqqOwZ9OOFSd_AXR-y7MjA?via=matrix.org&via=tchncs.de&via=grusbv.com)

so there's no way to get an irq on link change (in the general case. You could if the PHY has an irq output and you wire it up to an EXTI pin, but most boards don't.)

So the fix is to somehow do that polling in a background task, at some reasonable frequency (say, once every second), instead of hot-polling like we do now.

**Comment by xoviat** [comment]
@wyager #1653 likely resolves the issue. however, we need a minimal reproducer with multiprio eth to confirm.

**Comment by wyager** [comment]
Confirmed this is fixed. Lower-priority threads now run no problem @xoviat
