### ISSUE TITLE
embassy-executor/cortex-m: `wfe` interfering with RTT and flashing

### ISSUE THREAD

**Issue by sgoll** [embassy-rs/embassy#1742]
With features `arch-cortex-m` and `executor-thread`, the crate `embassy-executor` runs `wfe` inside the main loop to sleep between processing:

https://github.com/embassy-rs/embassy/blob/30358c435e29eae0be1a8d5a991794ed4ba264ab/embassy-executor/src/arch/cortex_m.rs#L68-L73

This is usually okay but it interferes with RTT and flashing on some devices, see https://github.com/rtic-rs/rtic/issues/561 for this in RTIC, and also:

- https://github.com/knurling-rs/probe-run/issues/128
- https://github.com/probe-rs/probe-rs/issues/350

The [SEGGER wiki](https://wiki.segger.com/RTT#Low-power_modes) gives us more hints to what is happening here:

> Many CPU cores support low-power modes to save power while waiting for an event or interrupt. On Cortex-M for example this is achieved by executing the WFI and WFE instructions. Unfortunately, the exact behavior during low-power modes is depending on the actual device (two devices from different vendors incorporating the same Cortex-M core may behave different).
> 
> - Some devices disable the whole debug unit during low-power modes, causing J-Link to lose the connection to the device.
> - Some keep the debug unit enabled but disable the internal flash and RAM, making it effectively impossible for J-Link to perform RTT requests while the target is in a low-power mode
> 
> As the target will be idle most of the time, using low-power modes will effectively make the usage of RTT impossible, as the target memory cannot be accessed 99% of the time while the application is running. Halting the target application will make the device to make up and RAM etc. becomes accessible again. This may be seen as effects like "RTT output is only seen each time the target is halted".
> 
> **Solution:** When using RTT, make sure that low-power modes are **not used**.

I propose to add a feature flag (or some other way) to override the instruction that is used in the main loop. With `nop` instead of `wfe`, users of such setups could continue using RTT and flashing at least in dev builds.

This should come with a warning either way: when using `wfe`, note that RTT and/or flashing may not be possible, and when using `nop`, note that low-power modes are not used and the device draws more power.

**Comment by Dirbaio** [comment]
Which exact chip are you running into this issue with? Many have bits you can set to prevent the debug port from sleeping even if the core is running a WFE. For example DBGMCU in STM32. These allow debugging through WFE without having to do code changes and without having to change the firmware's behavior.

**Comment by Dirbaio** [comment]
I believe on F2 it should be possible to fix this with DBGMCU, yes. `embassy-stm32` supports [turning on the DBGMCU bits](https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/lib.rs#L165), and it [does so by default](https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/lib.rs#L137). Perhaps there's some bug, or some other bit F2 needs.

> Would it be useful to mention this implication in the description of feature executor-thread?

Yes, of course. More docs is always good.

My position is we shouldn't add workarounds to the executor unless it's absolutely required to make it work on a chip. And even then, a user can always write their own executor using the `raw` API and make it do `nop` instead of `wfe`, so it's not strictly required that the workaround is inside `embassy-executor` itself. I think we should only do it if a significant amount of chips require it.

**Comment by BryceBeagle** [comment]
I'm running into this issue as well with an `stm32f411`. When using `executor-thread` with `cargo-embed` I have to force reset using the `BOOT0` and `NRST` pins before I can flash again. I am using `embassy_stm32::init()` with the default configuration. 

Force resetting everytime when flashing isn't the _worst_ thing in the world, but is somewhat annoying. Is this expected behavior/a limitation of this chip?

**Comment by Ridtt** [comment]
Maybe it's not annoying when you have board at table, but having limitation of remote connect and update software through SWD is depressing. I had really good time in the past with setup macbook -> wifi -> rpi -> stlink -> stm32 for comfortable remote development.

**Comment by Ridtt** [comment]
Latest RTIC default example (with async) does not have this issue btw (for stm32F411) so its probably possible to fix

**Comment by showier-drastic** [comment]
FYI STM32G4 also has this problem, that causes it very difficult to flash download without the reset pin (Usually gets Arm Dap error). I'm using the default RCC config, so `enable_debug_during_sleep` is true. Changing WFE to NOP solves this problem.

**Comment by wrs** [comment]
STM32F103 also has this problem, as I discovered after a frustrating day. OpenOCD and ST-Link won't connect after a power cycle, because the WFE instruction has been executed by the firmware before the debugger can connect.

A workaround (at least with cortex-debug in VS Code) is to use connect-under-reset by adding a line to `launch.json` (assuming you're using `openocd`):

```
"serverArgs": [ "-c", "reset_config srst_only srst_nogate connect_assert_srst" ],
```

The `ST-LINK_gdbserver` has a `--initialize-reset` switch that might work too, but I haven't tried it.

**Comment by justDeeevin** [comment]
@BryceBeagle Same chip, same problem. The advice of modifying the `DBGMCU` bits doesn't seem to be available with `embassy_stm32/stm32f411ce`. No control register available for modification is exposed by the `DBGMCU` struct.

Have you been able to find a workaround other than using the `NRST` and/or `BOOT0` pins?

**Comment by justDeeevin** [comment]
I realized I could just use the peripherals exposed by `stm32f` in addition to those exposed by `embassy_stm32`:
```rust
#[cfg(debug_assertions)]
{
    info!("Enabling debug mode");
    unsafe { stm32f4::stm32f411::DBGMCU::steal() }
        .cr()
        .modify(|_, w| {
            w.dbg_sleep().set_bit();
            w.dbg_standby().set_bit();
            w.dbg_stop().set_bit()
        });
    unsafe { stm32f4::stm32f411::RCC::steal() }
        .ahb1enr()
        .modify(|_, w| {
            w.dma1en().enabled();
            // Some bits that aren't in the workaround in probe-rs#350 that ChatGPT suggested
            w.dma2en().enabled();
            w.crcen().enabled()
        });
}
```

Unfortunately this has failed to fix the problem. TwT

**Comment by BryceBeagle** [comment]
Nope, never found a workaround unfortunately.

**Comment by justDeeevin** [comment]
I tried and tried but i'm ultimately stuck with a debug-only `keep_awake` task:
```rust
#[cfg(debug_assertions)]
#[task]
async fn keep_awake() {
    loop {
        cortex_m::asm::nop();
        Timer::after_millis(1).await;
    }
}
````

it hurts me in my soul but oh well
