### ISSUE TITLE
Proposition of example of QSPI usage on STM32

### ISSUE THREAD

**Issue by Mirror0** [embassy-rs/embassy#2921]
Hi @Dirbaio 

I was asked to provide example of QSPI usage here https://github.com/embassy-rs/embassy/issues/1293.

I would be happy to merge it into the example repository here, but it uses implementation for specific flash chip to demonstrate communication. It has hard-coded chip commands as constants so it is not very generic.

You can see full code here: https://github.com/Mirror0/qspi-example

And here is my question. Is example in this format acceptable?

**Comment by Dirbaio** [comment]
yes! it's fine if it's for one particular flash chip, it's an example after all. if the user has another flash chip they'll have to edit it, but at least they have a starting point.

i'd collapse it to a single .rs file and remove the need for `#![feature(type_alias_impl_trait)]` so it compiles on stable ,but otherwise it looks great! :+1:
