### ISSUE TITLE
Copyright holder name is missing in Apache license

### ISSUE THREAD

**Issue by andresv** [embassy-rs/embassy#472]
https://github.com/embassy-rs/embassy/blob/master/LICENSE-APACHE#L189

**Comment by lulf** [comment]
Should we change that from Copyright [yyyy] [name of copyright owner] to 

`Copyright 2022 Embassy project contributors`

I was also wondering about the LICENSE-MIT file as well @Dirbaio which is copyright in your name right now. Maybe it should have the same wording (up to you since you own the copyright it seems :)).
