### ISSUE TITLE
stm32/i2c: add async support to v1

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/embassy#620]
Possibly address together with #619

**Comment by barnabywalters** [comment]
Summary from matrix discussion:

* Ignore timeouts for the moment, implement the async API without any blocking loops so that users can handle timeouts themselves.
* Should be able to leave the v1 blocking API as it is, and add an async API similar to the one in https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/i2c/v2.rs
* The CI doesn’t include tests for I2C, so make an i2c_async example which uses the new API and use that on the available hardware for testing
