### ISSUE TITLE
rp2040-pac vs rp2040-pac2?

### ISSUE THREAD

**Issue by edisno** [embassy-rs/embassy#899]
Hello, I am curious why embassy uses "rp2040-pac2" while other crates i'd like to integrate use "rp2040-pac".  AFAICS, they are incompatible, and rp2040-pac is more complete.  Any possibilities or plans to migrate embassy to "rp2040-pac"?  Thanks for your efforts, embassy looks real nice.

**Comment by Dirbaio** [comment]
pac2 is generated by [chiptool](https://github.com/embassy-rs/chiptool) instead of svd2rust, which fixes some issues (see the README) and builds faster.

Note that you can use both PACs at the same time if you make sure the `rt` feature is enabled in only one of them.

> rp2040-pac is more complete

What have you found missing in pac2? just curious, since both are generated from the same SVD.
